language: r
sudo: required
bioc_required: true
warnings_are_errors: true

notifications:
  email:
    recipients:
      - jstorey@princeton.edu
      - ajbass@princeton.edu

apt_packages:
  - libnetcdf-dev

r_packages:
  - rmarkdown
  - dplyr
  - tidyr
  - broom
  - plyr
  - data.table
  - ggplot2
  - knitr
  
bioc_packages:
  - Biobase
  - limma
  - DESeq2
  - airway 
  - GenomicRanges
  - edgeR
  - qvalue
  - MSnbase
