language: r
sudo: required
bioc_required: true
r: bioc-devel
warnings_are_errors: true

bioc_packages:
  - Biobase
  - limma
  - DESeq2
  - airway 
  - GenomicRanges
  - edgeR
  - qvalue
  - MSnbase

notifications:
  email:
    recipients:
      - ajbass@princeton.edu

apt_packages:
  - netcdf-bin
  - libnetcdf-dev

r_packages:
  - testthat
  - rmarkdown
  - dplyr
  - tidyr
  - broom
  - plyr
  - data.table
  - ggplot2
  - knitr
